# Generated by Django 4.2 on 2023-06-21 18:07

import api.fields
import api.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, validators=[api.validators.validate_stock_code])),
                ('company_name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[api.validators.validate_cnpj])),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], max_length=1)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', api.fields.PositiveFloatField()),
                ('brokerage', api.fields.PositiveFloatField()),
                ('date', models.DateField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.investor')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='api.stock')),
            ],
        ),
    ]
